#!/bin/bash
function PortScan1 {
	read -p "Introduzca la direccion IP o el rango de IPs a escanear por ejemplo puede probar con ""127.0.0.1"" :" ip_range
	read -p "Intoduzca el rango de puertos a escanear (por ejemplo, 1-100): " port_range
	echo "Escaneando puertos con nmap..."
	nmap -p $port_range $ip_range -oG - | grep "/open" > nmap_results.txt
	echo "Verificando puertos abiertos con netcat..."
	while read -r line; do 
		ip=$(echo $line | awk '{print $2}')
		ports=$(echo $line | grep -oP '\d+/open' | cut -d '/' -f 1)
		for port in $ports; do 
			nc -zv $ip $port 2>&1 | grep -q "open" && echo "Puerto $port en $ip está abierto"
		done
	done < nmap_results.txt
}
function PortScan2 {
	read -p "Introduzca la direccion IP o el rango de IPs a escanear por ejemplo puede probar con ""127.0.0.1"" :" ip_range
	read -p "Intoduzca el rango de puertos a escanear (por ejemplo, 1-100): " port_range
	echo "Escaneando puertos con nmap..."
	echo "Verificando puertos abiertos con netcat..."
	nmap_output=$(nmap -p $port_range $ip_range -oG - | grep "/open")
	while read -r line; do 
		ip=$(echo $line | awk '{print $2}')
		ports=$(echo $line | grep -oP '\d+/open' | cut -d '/' -f 1)
		for port in $ports; do 
			nc -zv $ip $port 2>&1 | grep -q "open" && echo "Puerto $port en $ip está abierto"
		done
	done <<< "$nmap_output"
}
while true; do
    read -p "¿Para escanear los puertos desea generar un archivo txt donde se guarden los resultados del escaneo? (si no quiere ingrese n y si si quiere ingrese s): " var
    case $var in
        [sS])
            while true; do 
                PortScan1
                read -p "Desea ejecutar otra vez la funcion?(si no quiere ingrese n y si si quiere ingrese s): " fun
                case $fun in
                    [sS])
                        continue;;
                    [nN])
                        break;;
                    *)
                        echo "Opcion invalida, por favor ingrese (s/n)";;
                esac
            done
            break;;
        [nN])
            while true; do
                PortScan2
                read -p "Desea ejecutar otra vez la funcion?(si no quiere ingrese n y si si quiere ingrese s): " fun
                case $fun in
                    [sS])
                        continue;;
                    [nN])
                        break;;
                    *)
                        echo "Opcion invalida, por favor ingrese (s/n)";;
                esac
            done
            break;;
        *)
            echo "Opción inválida, por favor ingrese (s/n)";;
    esac
done
